[hugoVersion]
extended = false
min = "0.84.4"

[[mounts]]
source = "assets"
target = "assets"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "layouts"
target = "layouts"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/components/functions"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/debug"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/hooks"
